### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [pcbsd/lumina-i18n#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by bittin** [comment]
https://github.com/pcbsd/lumina/blob/master/LICENSE

?

**Comment by beanpole135** [comment]
Ah, looks like the guy who setup the lumina-i18n repo for storing the translation files did not copy the license file from the main Lumina repo over as well... Fixed!

https://github.com/pcbsd/lumina-i18n/commit/b0c03b92737142d0df760c87574814d1347af48a
