### ISSUE TITLE
ts/hi/lumina-fileinfo.ts does not parse

### ISSUE THREAD

**Issue by cpforbes** [pcbsd/lumina-i18n#2]
I get an error on the **ts/hi/lumina-fileinfo.ts** file using lrelease v5.6.0

**Comment by rapgro** [comment]
```
+ lrelease-qt5 lumina-i18n-fbab63ee19381741ee7f43329a276b89d6489425/ts/hi/lumina-fileinfo.ts -qm qm/hi_ts.qm
lrelease error: Unexpected tag <message> at lumina-i18n-fbab63ee19381741ee7f43329a276b89d6489425/ts/hi/lumina-fileinfo.ts:4:11
```

**Comment by beanpole135** [comment]
Fixed!!

https://github.com/trueos/lumina-i18n/commit/a96928d68364529cce670e4f64d9f988d5cc1a8c

**Comment by rapgro** [comment]
Broken again with auto commit, https://github.com/trueos/lumina-i18n/commit/8a4c4dbb093f11a8961b58d7ee1c6f8833a37d8d

**Comment by beanpole135** [comment]
Grr.. Something in the Pootle translation system has apparently cached the old/broken file and keeps re-committing the invalid version.
We are going to be turning off Pootle here soon and moving over to Weblate instead - so I might wait to fix this again until that changeover happens.

**Comment by rapgro** [comment]
Should I go with the official 1.0.0 tarball or keep a downstream patch for current snapshots? People may complain about missing / broken translations fixed upstream. FYI I'm the upcoming package maintainer in Fedora, currently a possible package is in review.

**Comment by beanpole135** [comment]
Yes, use the static 1.0.0-Release tarball if possible - that one has the correct version of the "hi" translation file.

I am only just now starting to make changes to the master branch which modify translation strings, and they are already working on the move to weblate, so I don't think you will have to worry about the master source translation being out-of-date for too long - maybe a week or two.
